services:
  - type: web
    name: restaurant-sop-notifier-wadee109
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
